from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class PaymentCreate(BaseModel):
    booking_id: str
    amount: float = Field(..., gt=0)
    payment_method: str = Field("CREDIT_CARD", min_length=3)
    # Strictly do not pass card number, expiry, CVV to satisfy PCI-DSS
    card_token: str = Field(..., description="Secure payment token generated by client side gateway integration")

class PaymentStatusPatch(BaseModel):
    payment_status: str = Field(..., pattern="^(PENDING|SUCCEEDED|FAILED)$")

class PaymentOut(BaseModel):
    payment_id: str
    booking_id: str
    amount: float
    payment_status: str
    payment_method: str
    transaction_reference: str
    created_at: str
