apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: aerolink
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 146697354183.dkr.ecr.us-east-1.amazonaws.com/dev-aerolink-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: USERS_TABLE_NAME
          value: "dev-UsersTable"
        - name: JWT_SECRET
          value: "aerolink-super-secret-jwt-key-2026"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: aerolink
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
