apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: aerolink
  labels:
    app: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: 146697354183.dkr.ecr.us-east-1.amazonaws.com/dev-aerolink-booking-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: BOOKINGS_TABLE_NAME
          value: "dev-BookingsTable"
        - name: SQS_BOOKING_RESOLUTION_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/146697354183/dev-aerolink-BookingResolutionQueue"
        - name: JWT_SECRET
          value: "aerolink-super-secret-jwt-key-2026"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: aerolink
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
